name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    env:
      Holiday__ApiKey: ${{ secrets.FINTUREST__HOLIDAY__APIKEY }}
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

    - name: Build
      run: dotnet build Finturest.Holiday.sln --configuration Release /p:ContinuousIntegrationBuild=true

    - name: Integration tests
      run: dotnet test tests/Finturest.Holiday.IntegrationTests --configuration Release --no-build
      
    - name: Pack Finturest.Holiday
      run: dotnet pack src/Finturest.Holiday --configuration Release --no-build --output nuget

    - name: Pack Finturest.Holiday.Abstractions
      run: dotnet pack src/Finturest.Holiday.Abstractions --configuration Release --no-build --output nuget

    - name: Upload artifacts
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/releases/')
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: nuget/

  publish:
    name: Publish
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/heads/releases/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: nuget

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Publish NuGet packages to NuGet
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "nuget.org"
